# Generated by Django 5.0 on 2023-12-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="candidate_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
