# Generated by Django 5.0 on 2023-12-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_candidate_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
